-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 30-Nov-2020 às 20:48
-- Versão do servidor: 10.4.16-MariaDB
-- versão do PHP: 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `sin143`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `host`
--

CREATE TABLE `host` (
  `ID` int(11) NOT NULL,
  `nome` varchar(60) NOT NULL,
  `CPF` varchar(11) NOT NULL,
  `email` varchar(50) NOT NULL,
  `telefone` varchar(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `host`
--

INSERT INTO `host` (`ID`, `nome`, `CPF`, `email`, `telefone`) VALUES
(1, 'Rafael Varão', '11111111122', 'rafaelvarao@contato.com.br', '(00) 22222-2222'),
(3, 'Ester Portela', '22222222233', 'esterportela@contato.com.br', '(00) 11111-1111'),
(4, 'Pablo Ramírez', '33333333344', 'pabloramirez@contato.com.br', '(00) 33333-3333');

-- --------------------------------------------------------

--
-- Estrutura da tabela `tipo_hospedagem`
--

CREATE TABLE `tipo_hospedagem` (
  `hostID` int(11) NOT NULL,
  `titulo` varchar(30) DEFAULT NULL,
  `descricao` text NOT NULL,
  `ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `tipo_hospedagem`
--

INSERT INTO `tipo_hospedagem` (`hostID`, `titulo`, `descricao`, `ID`) VALUES
(3, 'Cama Love Relaxante', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 1),
(3, 'Cama Casal Simples', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 2),
(3, 'Cama King Size', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 3),
(3, 'Cama Pequena', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 4),
(1, 'Cama Solteiro Simples', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 5),
(1, 'Cama Estudante', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 6),
(1, 'Cama Solteiro Dupla', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 7),
(4, 'Sofá Estiloso', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 8),
(4, 'Sofá com Cama', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 9),
(4, 'Sofá que Vira Cama', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 10),
(3, 'Rede ao ar Livre', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 11),
(3, 'Rede Simples', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.\r\n\r\nVestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 12),
(3, 'Rede Chique', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis in metus et sapien suscipit rutrum. Nam ultricies venenatis est quis bibendum. Sed commodo, diam vitae dapibus pharetra, purus quam blandit augue, ac efficitur enim risus vitae purus. Nam leo nibh, tincidunt vitae urna ac, lacinia sodales arcu. Nam sed viverra diam. Fusce libero lectus, imperdiet sit amet nisl sed, fringilla eleifend velit. Praesent eros velit, molestie congue convallis id, rutrum a purus. Suspendisse eget lacus et ex lobortis iaculis. Nullam faucibus ultrices lacinia. Vivamus suscipit turpis ligula, at porttitor mi ultrices quis. Aliquam pharetra commodo ligula, quis luctus orci gravida eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ultrices ultrices tellus, et sodales purus vestibulum sed. Sed in lobortis ipsum. Praesent sit amet sem dignissim, volutpat quam ac, posuere erat. Integer mi ligula, commodo non eros in, hendrerit fermentum lacus.  Vestibulum sit amet varius erat. Maecenas sit amet ornare risus. Fusce bibendum nisl ante, sed porttitor dui interdum facilisis. Aenean lobortis enim ante, ac malesuada velit ultrices sed. Etiam at posuere arcu, et sagittis tellus. Morbi commodo, ipsum eu faucibus aliquet, erat elit aliquam metus, ut blandit erat ante mollis ipsum. Aenean erat purus, sodales eu ipsum sit amet, semper pellentesque sem. Donec feugiat odio porttitor, vehicula ligula quis, fringilla dolor. Aliquam lacinia ut tortor at mattis. Quisque sed elementum nibh. Etiam congue ultrices sapien. Quisque dapibus gravida felis, condimentum commodo ligula porta eget. Nullam faucibus vitae metus vitae suscipit. Nulla consequat porta urna, vitae posuere leo tempor et. Suspendisse nec elit at dolor luctus suscipit a quis mauris.', 13),
(1, 'Teste', 'Teste', 26);

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `host`
--
ALTER TABLE `host`
  ADD PRIMARY KEY (`ID`);

--
-- Índices para tabela `tipo_hospedagem`
--
ALTER TABLE `tipo_hospedagem`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `titulo` (`titulo`),
  ADD KEY `hostID` (`hostID`),
  ADD KEY `hostID_2` (`hostID`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `host`
--
ALTER TABLE `host`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT de tabela `tipo_hospedagem`
--
ALTER TABLE `tipo_hospedagem`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- Restrições para despejos de tabelas
--

--
-- Limitadores para a tabela `tipo_hospedagem`
--
ALTER TABLE `tipo_hospedagem`
  ADD CONSTRAINT `tipo_hospedagem_ibfk_1` FOREIGN KEY (`hostID`) REFERENCES `host` (`ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
